version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands: 
      - cd reim-app-redux/buildspec.yml
      - npm install
  build:
    commands:
      - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: 'reim-app-redux/buildspec.yml'